import React, { useState, useEffect } from 'react';
import { X, Plus, Minus, Check, Trash2, ChevronLeft } from 'lucide-react';
import { useStore } from '../context/StoreContext';
import { OrderItem, Order, MenuItem } from '../types';
import { ITEM_ADDONS, ADDON_PRICES } from '../constants';

interface OrderModalProps {
  isOpen: boolean;
  onClose: () => void;
  orderToEdit?: Order | null;
}

const SECTIONS = [
  { id: 'Main', label: 'Mains' },
  { id: 'Sides', label: 'Extras' },
  { id: 'Kids', label: 'Kids' },
  { id: 'Drinks', label: 'Drinks' },
];

export const OrderModal: React.FC<OrderModalProps> = ({ isOpen, onClose, orderToEdit }) => {
  const { menu, addOrder, editOrder, deleteOrder } = useStore();
  const [cart, setCart] = useState<OrderItem[]>([]);
  const [customerName, setCustomerName] = useState('');
  const [selectedSection, setSelectedSection] = useState<string>('Main');

  // Customization State
  const [customizingItem, setCustomizingItem] = useState<MenuItem | null>(null);
  const [selectedAddons, setSelectedAddons] = useState<string[]>([]);

  useEffect(() => {
    if (isOpen) {
      if (orderToEdit) {
        setCart(orderToEdit.items);
        setCustomerName(orderToEdit.customerName);
      } else {
        setCart([]);
        setCustomerName('');
      }
      setSelectedSection('Main');
      setCustomizingItem(null);
      setSelectedAddons([]);
    }
  }, [isOpen, orderToEdit]);

  if (!isOpen) return null;

  const handleItemClick = (item: MenuItem) => {
    // Check if item has available addons
    const hasAddons = ITEM_ADDONS[item.name];

    if (hasAddons) {
      setCustomizingItem(item);
      setSelectedAddons([]);
    } else {
      addToCart(item, []);
    }
  };

  const toggleAddon = (addon: string) => {
    setSelectedAddons(prev => {
      if (prev.includes(addon)) {
        return prev.filter(a => a !== addon);
      } else {
        return [...prev, addon];
      }
    });
  };

  const confirmCustomization = () => {
    if (customizingItem) {
      addToCart(customizingItem, selectedAddons);
      setCustomizingItem(null);
      setSelectedAddons([]);
    }
  };

  const addToCart = (item: MenuItem, addons: string[]) => {
    setCart(prev => {
      // Check if exact item with same addons exists
      const existingIndex = prev.findIndex(i =>
        i.menuItemId === item.id &&
        JSON.stringify(i.addons?.sort()) === JSON.stringify(addons.sort())
      );

      if (existingIndex >= 0) {
        const newCart = [...prev];
        newCart[existingIndex].quantity += 1;
        return newCart;
      }

      return [...prev, {
        menuItemId: item.id,
        name: item.name === 'Deluxe Steak & Fries' ? 'Deluxe Steak' : item.name,
        price: item.price,
        quantity: 1,
        addons: addons
      }];
    });
  };

  const updateQuantity = (index: number, delta: number) => {
    setCart(prev => prev.map((item, i) => {
      if (i === index) {
        return { ...item, quantity: Math.max(0, item.quantity + delta) };
      }
      return item;
    }).filter(item => item.quantity > 0));
  };

  const calculateItemTotal = (item: OrderItem) => {
    let itemPrice = item.price;
    let freeSauceAvailable = item.name === 'Kids Meal';

    if (item.addons) {
      item.addons.forEach(addon => {
        let price = ADDON_PRICES[addon] || 0;
        const isSauce = ['Green Sauce', 'Red Sauce'].includes(addon);

        if (freeSauceAvailable && isSauce) {
          price = 0;
          freeSauceAvailable = false;
        }
        itemPrice += price;
      });
    }
    return itemPrice * item.quantity;
  };

  const total = cart.reduce((sum, item) => sum + calculateItemTotal(item), 0);

  const handleSubmit = () => {
    if (!customerName || cart.length === 0) return;

    if (orderToEdit) {
      const updatedOrder: Order = {
        ...orderToEdit,
        customerName,
        items: cart,
        total: total,
      };
      editOrder(updatedOrder);
    } else {
      const newOrder: Order = {
        id: '', // Will be generated by DB/Context
        customerName,
        status: 'cooking',
        items: cart,
        total: total,
        createdAt: new Date().toISOString(),
        estimatedTime: new Date(Date.now() + 15 * 60000).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
      };
      addOrder(newOrder);
    }

    setCart([]);
    setCustomerName('');
    onClose();
  };

  const handleDelete = () => {
    if (orderToEdit) {
      if (confirm('Are you sure you want to delete this order?')) {
        deleteOrder(orderToEdit.id);
        onClose();
      }
    }
  }

  const filteredMenu = menu.filter(m => m.category === selectedSection);

  return (
    <div className="fixed inset-0 bg-black/80 z-50 flex items-center justify-center backdrop-blur-sm p-4">
      <div className="w-full max-w-5xl bg-zinc-950 border border-zinc-800 rounded-3xl flex flex-col md:flex-row shadow-2xl overflow-hidden max-h-[90vh]">

        {/* Left: Menu Selection or Customization */}
        <div className="flex-1 flex flex-col border-r border-zinc-800 h-full overflow-hidden relative">
          {customizingItem ? (
            <div className="flex flex-col h-full animate-fade-in">
              <div className="p-6 border-b border-zinc-800 bg-zinc-900/50 flex items-center gap-4">
                <button
                  onClick={() => setCustomizingItem(null)}
                  className="p-2 hover:bg-zinc-800 rounded-full text-zinc-400 hover:text-white transition-colors"
                >
                  <ChevronLeft className="w-6 h-6" />
                </button>
                <div>
                  <h2 className="text-2xl font-bold text-white font-heading uppercase">Customize {customizingItem.name === 'Deluxe Steak & Fries' ? 'Deluxe Steak' : customizingItem.name}</h2>
                  <p className="text-zinc-400 text-sm">Select extras and sauces</p>
                </div>
              </div>

              <div className="flex-1 overflow-y-auto p-6 bg-zinc-950 space-y-8">
                {ITEM_ADDONS[customizingItem.name]?.extras && ITEM_ADDONS[customizingItem.name].extras.length > 0 && (
                  <div>
                    <h3 className="text-sm font-bold text-zinc-500 uppercase tracking-wider mb-4">Extras</h3>
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                      {ITEM_ADDONS[customizingItem.name].extras.map(addon => (
                        <button
                          key={addon}
                          onClick={() => toggleAddon(addon)}
                          className={`p-4 rounded-xl border text-left transition-all flex justify-between items-center ${selectedAddons.includes(addon)
                            ? 'bg-brand-yellow/10 border-brand-yellow text-white'
                            : 'bg-zinc-900 border-zinc-800 text-zinc-400 hover:border-zinc-700'
                            }`}
                        >
                          <span className="font-medium">{addon}</span>
                          <span className="text-sm font-bold text-brand-yellow">+£{ADDON_PRICES[addon]?.toFixed(2)}</span>
                        </button>
                      ))}
                    </div>
                  </div>
                )}

                {ITEM_ADDONS[customizingItem.name]?.sauces && ITEM_ADDONS[customizingItem.name].sauces.length > 0 && (
                  <div>
                    <h3 className="text-sm font-bold text-zinc-500 uppercase tracking-wider mb-4">Sauces</h3>
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                      {ITEM_ADDONS[customizingItem.name].sauces.map(sauce => {
                        const isFree = customizingItem.name === 'Kids Meal' && !selectedAddons.some(a => ['Green Sauce', 'Red Sauce'].includes(a) && a !== sauce);
                        return (
                          <button
                            key={sauce}
                            onClick={() => toggleAddon(sauce)}
                            className={`p-4 rounded-xl border text-left transition-all flex justify-between items-center ${selectedAddons.includes(sauce)
                              ? 'bg-brand-yellow/10 border-brand-yellow text-white'
                              : 'bg-zinc-900 border-zinc-800 text-zinc-400 hover:border-zinc-700'
                              }`}
                          >
                            <span className="font-medium">{sauce}</span>
                            {ADDON_PRICES[sauce] && !isFree ? (
                              <span className="text-sm font-bold text-brand-yellow">+£{ADDON_PRICES[sauce]?.toFixed(2)}</span>
                            ) : (
                              <span className="text-xs font-bold text-zinc-500 uppercase">Free</span>
                            )}
                          </button>
                        )
                      })}
                    </div>
                  </div>
                )}

                {ITEM_ADDONS[customizingItem.name]?.drinks && ITEM_ADDONS[customizingItem.name].drinks.length > 0 && (
                  <div>
                    <h3 className="text-sm font-bold text-zinc-500 uppercase tracking-wider mb-4">Drinks</h3>
                    <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                      {ITEM_ADDONS[customizingItem.name].drinks.map(drink => (
                        <button
                          key={drink}
                          onClick={() => toggleAddon(drink)}
                          className={`p-4 rounded-xl border text-left transition-all flex justify-between items-center ${selectedAddons.includes(drink)
                            ? 'bg-brand-yellow/10 border-brand-yellow text-white'
                            : 'bg-zinc-900 border-zinc-800 text-zinc-400 hover:border-zinc-700'
                            }`}
                        >
                          <span className="font-medium">{drink}</span>
                          <span className="text-sm font-bold text-brand-yellow">+£{ADDON_PRICES[drink]?.toFixed(2)}</span>
                        </button>
                      ))}
                    </div>
                  </div>
                )}
              </div>

              <div className="p-6 border-t border-zinc-800 bg-zinc-900">
                <button
                  onClick={confirmCustomization}
                  className="w-full py-4 bg-brand-yellow text-black font-bold text-lg rounded-xl hover:bg-yellow-400 transition-all shadow-lg shadow-yellow-900/20"
                >
                  Add to Order
                </button>
              </div>
            </div>
          ) : (
            <>
              <div className="p-6 border-b border-zinc-800 bg-zinc-900/50">
                <div className="flex items-center justify-between mb-4">
                  <h2 className="text-2xl font-bold text-white font-heading uppercase">{orderToEdit ? 'Edit Order' : 'New Order'}</h2>
                </div>

                <div className="flex gap-2 overflow-x-auto no-scrollbar">
                  {SECTIONS.map(section => (
                    <button
                      key={section.id}
                      onClick={() => setSelectedSection(section.id)}
                      className={`px-6 py-3 rounded-xl text-sm font-bold whitespace-nowrap transition-all flex-1 border-2 ${selectedSection === section.id
                        ? 'bg-brand-yellow text-black border-brand-yellow'
                        : 'bg-zinc-900 text-zinc-400 border-zinc-800 hover:border-zinc-700 hover:text-white'
                        }`}
                    >
                      {section.label}
                    </button>
                  ))}
                </div>
              </div>

              <div className="flex-1 overflow-y-auto p-6 bg-zinc-950">
                <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
                  {filteredMenu.map(item => (
                    <button
                      key={item.id}
                      onClick={() => handleItemClick(item)}
                      className="flex flex-col items-start p-4 bg-zinc-900 border border-zinc-800 rounded-xl hover:border-brand-yellow transition-all group text-left hover:shadow-lg hover:shadow-yellow-900/10"
                    >
                      <div className="flex justify-between w-full mb-2">
                        <span className="font-bold text-white text-sm">{item.name === 'Deluxe Steak & Fries' ? 'Deluxe Steak' : item.name}</span>
                        <span className="font-bold text-brand-yellow text-sm">£{item.price.toFixed(2)}</span>
                      </div>
                      {ITEM_ADDONS[item.name] && (
                        <div className="mt-2 text-xs text-brand-yellow font-medium uppercase tracking-wide">
                          Customizable
                        </div>
                      )}
                    </button>
                  ))}
                  {filteredMenu.length === 0 && (
                    <div className="col-span-full text-center py-12 text-zinc-500">
                      No items in this category.
                    </div>
                  )}
                </div>
              </div>
            </>
          )}
        </div>

        {/* Right: Cart Details */}
        <div className="w-full md:w-[380px] flex flex-col bg-zinc-900 h-full border-l border-zinc-800">
          <div className="p-6 border-b border-zinc-800 flex justify-between items-center bg-zinc-800/50">
            <h3 className="font-bold text-white text-lg font-heading uppercase">Order Details</h3>
            <button onClick={onClose} className="p-2 hover:bg-zinc-800 rounded-full text-zinc-400 hover:text-white transition-colors">
              <X className="w-5 h-5" />
            </button>
          </div>

          <div className="p-4 border-b border-zinc-800 bg-zinc-900/50">
            <input
              type="text"
              value={customerName}
              onChange={(e) => setCustomerName(e.target.value)}
              placeholder="Customer Name / Table No."
              className="w-full bg-zinc-950 border border-zinc-800 rounded-xl px-4 py-3 text-white focus:ring-2 focus:ring-brand-yellow focus:outline-none font-medium"
              autoFocus
            />
          </div>

          <div className="flex-1 overflow-y-auto p-4 space-y-3 bg-zinc-900">
            {cart.length === 0 ? (
              <div className="h-full flex flex-col items-center justify-center text-zinc-500 space-y-2 opacity-50">
                <div className="p-4 bg-zinc-800 rounded-full">
                  <Plus className="w-6 h-6" />
                </div>
                <p>Add items from menu</p>
              </div>
            ) : (
              cart.map((item, idx) => (
                <div key={idx} className="bg-zinc-950 p-3 rounded-xl border border-zinc-800 flex justify-between items-start group hover:border-zinc-700 transition-colors">
                  <div className="flex-1">
                    <div className="font-bold text-white text-sm">{item.name}</div>
                    {item.addons && item.addons.length > 0 && (
                      <div className="mt-1 space-y-0.5">
                        {item.addons.map((addon, aIdx) => (
                          <div key={aIdx} className="text-xs text-zinc-500 flex items-center gap-1">
                            <span className="w-1 h-1 rounded-full bg-zinc-700"></span>
                            {addon}
                          </div>
                        ))}
                      </div>
                    )}
                    <div className="text-brand-yellow text-xs font-bold mt-1">£{calculateItemTotal(item).toFixed(2)}</div>
                  </div>
                  <div className="flex items-center gap-3 bg-zinc-900 rounded-lg p-1 border border-zinc-800 h-fit">
                    <button onClick={() => updateQuantity(idx, -1)} className="w-7 h-7 flex items-center justify-center hover:bg-zinc-800 rounded text-zinc-400 hover:text-white transition-colors"><Minus className="w-3 h-3" /></button>
                    <span className="text-sm font-bold w-5 text-center text-white">{item.quantity}</span>
                    <button onClick={() => updateQuantity(idx, 1)} className="w-7 h-7 flex items-center justify-center hover:bg-zinc-800 rounded text-zinc-400 hover:text-white transition-colors"><Plus className="w-3 h-3" /></button>
                  </div>
                </div>
              ))
            )}
          </div>

          <div className="p-6 bg-zinc-950 border-t border-zinc-800">
            <div className="flex justify-between items-end mb-4">
              <span className="text-zinc-400 font-medium">Total Amount</span>
              <span className="text-3xl font-bold text-white">£{total.toFixed(2)}</span>
            </div>
            <div className="flex gap-3">
              {orderToEdit && (
                <button
                  onClick={handleDelete}
                  className="p-4 bg-zinc-900 border border-zinc-800 text-zinc-400 rounded-xl hover:text-red-400 hover:bg-red-900/10 hover:border-red-900/30 transition-all"
                >
                  <Trash2 className="w-5 h-5" />
                </button>
              )}
              <button
                onClick={handleSubmit}
                disabled={!customerName || cart.length === 0}
                className="flex-1 py-4 bg-brand-yellow text-black font-bold text-lg rounded-xl hover:bg-yellow-400 disabled:opacity-50 disabled:cursor-not-allowed transition-all shadow-lg shadow-yellow-900/20 flex justify-center items-center gap-2 uppercase tracking-wide"
              >
                <Check className="w-5 h-5" /> {orderToEdit ? 'Update Order' : 'Confirm Order'}
              </button>
            </div>
          </div>
        </div>

      </div>
    </div>
  );
};